USE DATABASE DEMO_WS;
USE SCHEMA WORKSHOP;

CREATE OR REPLACE PROCEDURE SP_CARGAR_CLIENTES_DEMO()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    INSERT INTO DEMO_CLIENTES VALUES
    (3, 'Cliente C (SP)', CURRENT_DATE()),
    (4, 'Cliente D (SP)', CURRENT_DATE());

    RETURN 'OK - Datos insertados desde SP';
END;
$$;

-- Ejecutar SP
CALL SP_CARGAR_CLIENTES_DEMO();

-- Ver resultados
SELECT * FROM DEMO_CLIENTES;
